image: openjdk:11

clone:
  depth: full              # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build-content
        name: Build, test - content
        caches:
          - gradle
        script:
          - ./gradlew build
        artifacts:
          - build/classes/**
          - build/jacoco/**
          - build/libs/**

    - step: &sonar
        name: analyze on SonarCloud
        caches:
          - gradle
          - sonar
        script:
          - bash ./gradlew sonarqube -x test -Dsonar.projectKey=sgla_aiml-core -Dsonar.organization=sgla-bitbucket -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

    - step: &spotless
        name: analyse Code-Style
        caches:
          - gradle
        script:
          -  ./gradlew spotlessCheck
pipelines:
  branches:
    '**':
      - step: *build-content
      - parallel:
        - step: *sonar
        - step: *spotless
  pull-requests:
    '**':
      - step: *build-content
      - parallel:
        - step: *sonar
        - step: *spotless